### ISSUE TITLE
Magnetophon playback

### ISSUE THREAD

**Issue by metalthrow** [TomWhitwell/TuringMachine#112]
I have a Magnetophon with an external playback head. When rubbing the tape head across tape stuck to a sheet of foamcore or hard paper, I've tried both, it just sounds like the back of a credit. I'm wondering if anyone has experimented with this and knows if it is possible to obtain the cassette's actual sounds on it when manually pushing the head on to the tape?
<img width="610" alt="Screen Shot 2019-03-26 at 7 49 06 AM" src="https://user-images.githubusercontent.com/38014582/54994852-a9466980-4f9b-11e9-8361-2f9618d8f6e9.png">

**Comment by TomWhitwell** [comment]
Closed as duplicate, replied here https://github.com/TomWhitwell/Magnetophon/issues/8
