### ISSUE TITLE
Lock problem

### ISSUE THREAD

**Issue by mikisos** [TomWhitwell/TuringMachine#126]
Finished Turing Machine build. While trying to calibrate as stated in the video a problem occurs:

When the 1M trimmer is turned fully clockwise, the pattern locks on every position on the big knob. When trimmer is turned in any other position anti clockwise the pattern doesn’t lock at all, regardless of the big knob position. Gives a feeling that the trimmer scaling would be totally wrong or something.

Leds, noise and everything else seems to be working. Could you guide me towards a solution, please?

Pics attached. The extra jump wire from ferrite to elcap is because original lead was lost while desoldering an elcap which appeared to be too tall.

![8CBAAF58-359C-48C7-A209-657EEB82BFE8](https://user-images.githubusercontent.com/60555004/73598693-3d7e4700-4544-11ea-8e9c-02557e419c7b.jpeg)
![8F7FD975-4BB5-43F7-942B-70ABC9533381](https://user-images.githubusercontent.com/60555004/73598694-3d7e4700-4544-11ea-9af2-648807356543.jpeg)
![B9A6E1BF-577F-4DCF-9AC4-7BF2DE0FEADC](https://user-images.githubusercontent.com/60555004/73598695-3d7e4700-4544-11ea-9c8a-1e5798009493.jpeg)
![936B53C1-571D-4212-B7F4-CC9AD3511BF1](https://user-images.githubusercontent.com/60555004/73598696-3d7e4700-4544-11ea-80b1-0481df70bbe7.jpeg)
![655A9051-E630-4B3D-86DC-D298FD144998](https://user-images.githubusercontent.com/60555004/73598697-3e16dd80-4544-11ea-99b4-c369ee67df18.jpeg)
![3D098236-4330-496F-8CDD-D96844A91C83](https://user-images.githubusercontent.com/60555004/73598698-3e16dd80-4544-11ea-9892-db4d25f74128.jpeg)

**Comment by mikisos** [comment]
Hi again,
I’ve been going through the connections with the schematics. Should R22 connect to 1M trimmer? There is no connection so I may be having a cold joint there.

**Comment by TomWhitwell** [comment]
From this schematic: https://musicthing.co.uk/collateral/TuringMachine_schematic.pdf there is no connection between R22 and the trimmer - but R32 should be connected. 

Tom

**Comment by mikisos** [comment]
﻿Hi,
sorry I was mistaken. What I was meaning to ask was that should there be a connection between R22 and 50K change pot because there is none.

I got another Turing to switch boards and thus be able to narrow the problem. My back pcb works well with another front board so the problem is definitely on my front panel.

Best,
Mikko

>> Tom Whitwell <notifications@github.com> kirjoitti 5.2.2020 kello 8.35:
> ﻿From this schematic: https://musicthing.co.uk/collateral/TuringMachine_schematic.pdf there is no connection between R22 and the trimmer - but R32 should be connected. 
> 
> Tom 
>

**Comment by mikisos** [comment]
Hello again,
Sorry for the inconvenience. The connections seemed to be right after all. Just very difficult to calibrate -just a tad anti clockwise from the maximum trimmer position seemed to give the right result.

Thank you for help!
Best regards,
Mikko

> Tom Whitwell <notifications@github.com> kirjoitti 5.2.2020 kello 8.35:
> 
> ﻿From this schematic: https://musicthing.co.uk/collateral/TuringMachine_schematic.pdf there is no connection between R22 and the trimmer - but R32 should be connected. 
> 
> Tom 
>
