### ISSUE TITLE
Turing Machine - Length options

### ISSUE THREAD

**Issue by SYNTHOLABO** [TomWhitwell/TuringMachine#129]
Hi all,

Anyone know if the length can be set to 7 somehow?
What an oversight in design if not!
It's the best time signature IN THE UNIVERSE

Thanks for advice before I commit to getting a TM.

**Comment by TomWhitwell** [comment]
Hi, you could hack it by cutting a trace or two but it doesn’t some with 7 steps I’m afraid

**Comment by SYNTHOLABO** [comment]
Thanks Tom.
I'll look into this a bit deeper... with some help.
Do you think it will be a case of **substituting** one of the other settings for a 7 option?
