### ISSUE TITLE
Turing Machine gets stuck on one note when set to 8 steps or higher

### ISSUE THREAD

**Issue by saunlani** [TomWhitwell/TuringMachine#139]
Turing Machine works as expected, except it will only play a single note if the length is set to 8 or higher.  I don't believe this is expected.

I have checked the board for cold solder joints.

Any help is appreciated, thanks!

**Comment by saunlani** [comment]
I've tried two brand new TL074CN's

**Comment by TomWhitwell** [comment]
This might be an issue with one of the 4015 shift registers. Swap the two chips to see what happens. If the module becomes more broken, then replace those chips. If no change, the error may be elsewhere.

**Comment by TomWhitwell** [comment]
This might be an issue with one of the 4015 shift registers. Swap the two chips to see what happens. If the module becomes more broken, then replace those chips. If no change, the error may be elsewhere.

**Comment by TomWhitwell** [comment]
This might be an issue with one of the 4015 shift registers. Swap the two chips to see what happens. If the module becomes more broken, then replace those chips. If no change, the error may be elsewhere.

**Comment by saunlani** [comment]
I also did that, no change.  I noticed an issue when calibrating though.  No sound is produced when the big knob is turned all the way to the right.

**Comment by saunlani** [comment]
ended up reflowing everything on the front board and it works

**Comment by TomWhitwell** [comment]
That’s great news

**Comment by TomWhitwell** [comment]
That’s great news
