### ISSUE TITLE
TM Stops working When Clock Is Connected

### ISSUE THREAD

**Issue by zburns12** [TomWhitwell/TuringMachine#144]
Hey Tom,

I’ve double and triple checked my solder joints and IC connections to the best of my ability.

When I plug in the module, everything lights up as it should. But when I put a clock into it, the Clock LED lights up and the rest of it shuts down. I’m using a square wave output from a VCO for clock. I can see the Scale knob working via oscilloscope before I plug in the clock. Turning off and back on resets the lights. A few times, I have seen the lights on top start running for a split second and then it all goes dark. I don’t get any more than a blip of sound and have tested at multiple trim pot positions. I’m at a loss of what to check now. 

Any ideas? 

Thanks

Video of behavior: https://vimeo.com/472416867 

![5DF35351-1C42-468A-BA79-F48F8983DC42](https://user-images.githubusercontent.com/3279024/97241167-e1d0a980-17b5-11eb-93ee-674f628807b3.jpeg)
![A5A51E08-9A88-4742-A9A5-E3D1A1958A37](https://user-images.githubusercontent.com/3279024/97241175-e85f2100-17b5-11eb-81a9-4b490198a70c.jpeg)
![DEC4BD1D-12ED-4DFC-9480-D932D17BD438](https://user-images.githubusercontent.com/3279024/97241180-ebf2a800-17b5-11eb-9238-4d372c203fad.jpeg)
![2BD1AB12-7A72-4A67-A353-0A6B6CC37841](https://user-images.githubusercontent.com/3279024/97241187-ef862f00-17b5-11eb-9eaa-9eeafc38c487.jpeg)

**Comment by TomWhitwell** [comment]
Hi Zach, sorry to hear that - could I ask where you got your boards from? 
Was the clock input in the video at audio rates, or like a sequencer pulse?

**Comment by zburns12** [comment]
Hi Tom,

I got them from a US based store, https://www.sherpamodular.com/. 

The clock input was at audio rate, C4ish. I tried the square wave out of my Mangrove and TS-L.

**Comment by TomWhitwell** [comment]
Hi, you'd have to ask Sherpa modular for support for these boards. I can't offer this kind of support on non-Thonk boards.
