### ISSUE TITLE
Screw thread on blue trimmer extremely worn. Replaceable?

### ISSUE THREAD

**Issue by fjclarkson** [TomWhitwell/TuringMachine#146]
Hi,

I am new to eurorack DIY projects and did not actually build the Turing Machine MKII that I own - I am 19 with little experience in soldering so if this is a silly question please forgive. A while after I acquired the module I realised that it had problems introducing randomness when not fully locked both CCW and anti-CCW and so decided to attempt to recalibrate the module. After a few tries I quickly noticed that the thread on the calibration trimmer screw was extremely worn and so wouldn’t be turned by a screwdriver. I have removed the face plate and had a further look at the trimmer and have still had no success in turning it. Is there a way that I can replace the whole blue trimmer unit? Do u have any suggestions as to how I can solve this problem. Please enlighten me if you do I would be eternally grateful! 

Thanks,
Finn Clarkson

**Comment by TomWhitwell** [comment]
Hi Finn 
The best thing to do is to contact support@thonk.co.uk to see if they can sell you a blue trimmer
Tom
