### ISSUE TITLE
Finished my build, Calibration almost impossible, random sequence for half the steps

### ISSUE THREAD

**Issue by CITruesilver** [TomWhitwell/TuringMachine#147]
I just finished building the module and I have great difficulties to calibrate it. I rechecked all the components and they are all in place and soldered correctly (as far as I can tell).

When I feed the module a clock from an osc (square wave) and start calibrating I need to turn the potentiometer all the way CCW in order to get a stable tone. When I try to use the module as a random sequencer it generates a random sequence for approx. half the steps and the rest of the steps are a single tone. The clock input works as it should and the LED confirmes the pulses. Also the LEDs on the top seem to work as well. When I start reducing scale the 'randomness' disappears until gone completely.

Also even when turning the potentiometer a little bit more CW the sequence is not reaching random notes for the full length. Does anybody have an idea what could be causing this? It seems that I am not the only one having the calibration issues but unfortunately nobody has so far offered an explanation or solution.

![IMG_20210103_111347_resized_20210103_010155413](https://user-images.githubusercontent.com/76904724/103478219-50893f00-4dc5-11eb-92a3-f40427b06612.jpg)
![IMG_20210103_111358_resized_20210103_010155666](https://user-images.githubusercontent.com/76904724/103478221-5121d580-4dc5-11eb-9686-fa69ed520a2a.jpg)
![IMG_20210103_111409_resized_20210103_010155900](https://user-images.githubusercontent.com/76904724/103478223-51ba6c00-4dc5-11eb-97da-5f2905fee6ab.jpg)
![IMG_20210103_111419_resized_20210103_010156095](https://user-images.githubusercontent.com/76904724/103478224-52530280-4dc5-11eb-8dbb-e32d6be08522.jpg)
![IMG_20210103_112019_resized_20210103_010156296](https://user-images.githubusercontent.com/76904724/103478225-52eb9900-4dc5-11eb-99ff-b60c20fe0e87.jpg)
![IMG_20210103_112022_resized_20210103_010156502](https://user-images.githubusercontent.com/76904724/103478226-53842f80-4dc5-11eb-8884-8a008ad722d3.jpg)
![IMG_20210103_112123_resized_20210103_010156752](https://user-images.githubusercontent.com/76904724/103478227-53842f80-4dc5-11eb-8d78-0551a2769d31.jpg)

**Comment by Thonk-Steve** [comment]
Hey Frank, let's continue this one via the Muffwiggler thread or via the
thonk support email you already started.
