### ISSUE TITLE
Volts only outputing very low Rang

### ISSUE THREAD

**Issue by TimiRose** [TomWhitwell/TuringMachine#148]
Hi everybody, dear Tom, I built two Volts modules. One seems to work like expected and it´s just great, the other one has a very limited range in the low range. Where could the fault be?
Greetings, Tim

**Comment by TomWhitwell** [comment]
Hi, there’s not much to a Volts 

https://musicthing.co.uk/collateral/Volts_Schematic.pdf 

Check the op amp is installed correctly + seated correctly and look for shorts or missed pins 

Good luck!

**Comment by TimiRose** [comment]
Hi Tom,
the only thing I can really think of is that I didn´t solder the resistors in the same directions. But otherwise everything seems fine as far as I can see...I attached two Fotos.
Greetings, Tim

![IMG_1651](https://user-images.githubusercontent.com/74684836/105719976-2d186680-5f23-11eb-88c8-a2d07531e69d.jpeg)

![IMG_1652](https://user-images.githubusercontent.com/74684836/105719998-343f7480-5f23-11eb-8f23-0f0cacf17d54.jpeg)

**Comment by TomWhitwell** [comment]
Not sure, but the solder points on the op amp look a little bit thin?

**Comment by TimiRose** [comment]
Okay, I´ll redo those later. Difficult to get a good resolution photos with the phone. Thanks!

**Comment by TimiRose** [comment]
Ok, sorry about that, the thin solder points on the op amp were the cause like you suspected. Works fine now.
Thanks for the quick help!!
Tim
