### ISSUE TITLE
Electrolytic 10uF Capacitors

### ISSUE THREAD

**Issue by biospherix** [TomWhitwell/TuringMachine#159]
Hi,

I stupidly broke off one of the leads on a Electrolytic 10uF capacitor. I can easily get a replacement but my question is:

The voltage in the manual shows 100v, but the actual component is 35v. Does it matter if I use 100v, or 35v? 

Thanks.

**Comment by TomWhitwell** [comment]
Hi, anything above 12v is **theoretically** OK, but I'd say that 35v was ideal, or anything above that.

**Comment by Thonk-Steve** [comment]
anything 35V and up is fine 👍

Steve
Thonk

**Comment by biospherix** [comment]
Awesome, thanks for the super quick response, appreciate your help.
