### ISSUE TITLE
Unusual effect on powering up

### ISSUE THREAD

**Issue by davb2022** [TomWhitwell/TuringMachine#170]
I have just built a Turing Machine and have obliviously taken a wrong turn somewhere.  When I turn on the power supply my Tiptop Zeus and any of my other modules with led's flash on and off at a steady rate.  I didn't leave it on for too long as I didn't want to blow anything, has anybody any ideas?

**Comment by Thonk-Steve** [comment]
Hey, it sounds like you may have a short circuit somewhere in the PCB,
although it's not normally so intense! Do you have a digital multimeter?
Where did you buy the PCB?

**Comment by davb2022** [comment]
Sorted Hurrah! Unfortunately, in the excitement of almost being finished I had mounted the ic socket for DAC0800 the wrong way round and so I plugged the ic in the wrong way round, DOH.

**Comment by davb2022** [comment]
Thanks Steve for taking the time to answer, I actually bought the kit from your business.  Must try harder next time.

**Comment by Thonk-Steve** [comment]
Oh don't worry we've all done that plenty of times :) glad it's working!
