### ISSUE TITLE
Soldering length switch 

### ISSUE THREAD

**Issue by chriseccles73** [TomWhitwell/TuringMachine#177]
Apologies for the total noob question but I’ve built the Turing machine and was unsure about one thing. On the length switch, there is no metal on the pcb holes for the two crooked pins on either side of the switch. Do I solder these pins or are they just holding pins?

**Comment by Thonk-Steve** [comment]
You are fine to not solder these as mechanically it's very solid if the row
of pins is soldered and the nut and washers attach it to the panel.

**Comment by chriseccles73** [comment]
Thanks Steve. Much appreciated
