### ISSUE TITLE
Turing machine plays same high pitched notes

### ISSUE THREAD

**Issue by Thirteenmoons** [TomWhitwell/TuringMachine#186]
My TM will genterate a random pattern every so often however; upon locking it plays the same high pitched notes.  It often plays these notes for a bit before deciding to create a new random pattern

**Comment by Thonk-Steve** [comment]
Hi, could you send a video of what you're describing?

**Comment by Thirteenmoons** [comment]
Thanks for helping

**Comment by Thirteenmoons** [comment]
Thank for helping

**Comment by Thirteenmoons** [comment]
Thank you for taking the time to help. 


[https://vimeo.com/771781092]()

**Comment by Thirteenmoons** [comment]
Incidentally, the other modules seem to work fine.

**Comment by Thirteenmoons** [comment]
My link seemed to be wonky…


https://vimeo.com/771781092

**Comment by Thirteenmoons** [comment]
If you need a longer video or a demonstration of anything please let me know.

**Comment by Thirteenmoons** [comment]
Thanks
