### ISSUE TITLE
Any advice for sourcing DAC0800LCN 

### ISSUE THREAD

**Issue by phpguru** [TomWhitwell/TuringMachine#187]
Hey Tom, 

Looks like I can get every IC needed for a build except for the DAC. Mouser says more are expected 2024! I read your BOM about cheap Chinese knockoffs and would like to know if you have any other recommendations where to source this IC. Digikey & Farnell (Newark) were also a no go. Since I bought a panel pcb only, do you happen to know if Thonk will sell me just the parts bag? Or maybe a possible alternative? Is there an 0805 SMD + 16-dip conversion board version maybe?

Also as a long time GitHub user, if an issue is solved you should close it. Do you want help managing issues?

Cheers, Geoff

**Comment by Thonk-Steve** [comment]
Hi Geoff, drop us a line on ***@***.*** and we can help you out 👍

**Comment by phpguru** [comment]
Thanks Steve, I’m guessing it’s the Thonk support email?

**Comment by deepiain** [comment]
I’ve built 100’s of projects and I’ve never had any issues buying chips from eBay and Ali express.. not sure it’s as much of a minefield as people make out Sent from my iPhoneOn 20 Nov 2022, at 14:44, Geoffrey Hoffman ***@***.***> wrote:﻿
Thanks Steve, I’m guessing it’s the Thonk support email?

**Comment by TomWhitwell** [comment]
@phpguru Yes, it will be support@thonk.co.uk - not sure why the address was obfuscated
And yes, help managing issues would be great - I'm not a very confident GitHub user
