### ISSUE TITLE
TM2 locks with all lights steady and bright after a minute or so

### ISSUE THREAD

**Issue by alphonsom** [TomWhitwell/TuringMachine#201]
Newly built Turing Machine behaves for a minute or less, then all the LEDs light up fully bright and steady, and output ceases. It is calibrated as far as is possible within the time allowed before lockup. Even in the locked state, noise output is normal, and so is pulse output. Any hints or direction about where to look would be appreciated.

**Comment by Thonk-Steve** [comment]
That's an unusual one. What do you have to do to get it working again?

**Comment by alphonsom** [comment]
Switch off the power, and switch it back on again. Then the TM starts with all LEDs bright for a few seconds, followed by them going off in sequence from left to right in time with the incoming clock. Then there is a pause where all is dark for a few seconds. Then the normal behaviour starts for a while, and we go back to the beginning.

**Comment by Thonk-Steve** [comment]
Hey, what are you clocking it with?

**Comment by alphonsom** [comment]
A square wave out of an AI 011 VCO for calibration, or a clock signal from a Frequency Central Wave Runner LFO for normal. Same thing happens with either.

**Comment by TomWhitwell** [comment]
That's a real mystery - is there any effect on the other modules in the case - sounds like a power problem but I'm sure you've looked at that.

**Comment by alphonsom** [comment]
There is no effect on any other module. I tried a different power supply and cables just to be sure, and the behaviour is the same. Could something be causing a draining of randomness on the shift register return switch? Or a gradual inversion failure?

**Comment by Thonk-Steve** [comment]
Hi, did you build the module yourself? Did you use the IC pack from a Thonk
kit?

**Comment by alphonsom** [comment]
Yes to both questions.

**Comment by Thonk-Steve** [comment]
Ok the best step next would be to remove the front panel and post good
photos of both sides of both PCBs.

**Comment by alphonsom** [comment]
Aha. I combed its hair and washed its face for the photos, and noticed a couple of joints that I was sure you'd be telling me to reflow.  So I pre-empted - reflowed, tested, and it all works lovely. Thanks for your time.
