### ISSUE TITLE
Pots wrong way round

### ISSUE THREAD

**Issue by Bazzard** [TomWhitwell/TuringMachine#25]
Hi Tom,
In my eagerness to complete my Turing Machine, I managed to put the main 'sequence' pot and the scale pot in eachother's slots.
Can I leave as is - I'm hoping the pots are wired the same - or do I need to dismantle, desolder and get depressed....?
Any advice much appreciated.
Cheers,
Barry

**Comment by Thonk-Steve** [comment]
They are the same value so they will work fine.. you'll just be left with no knob on the scale pot :)

**Comment by Bazzard** [comment]
Ta for the speedy reply - and I'll work something out aesthetically for the scale pot...!
Cheers again,
Barry
