### ISSUE TITLE
Calibrating question

### ISSUE THREAD

**Issue by jurekprzezdziecki** [TomWhitwell/TuringMachine#28]
hi,

i have mate all boards together and started a calibrating process. I don't know if i do it right.

1. You said use a SQUARE output to calibrating TM - i have used fast rate CLOCK (pulse) output fro SSF URA - is it ok? or do i need PULSE wave output from an oscillator?

2. i get that stable, sustained tone only when trimmer is set totally anti clockwise - you say it's wrong because of a range set. what do you suggest?

3. Should be trimmer set clockwise BEFORE powering up the Turing Machine? or it does not matters for the calibrating process?

Thanks Jurek

**Comment by TomWhitwell** [comment]
1. Square or pulse should be fine 
2. I don't understand what you mean about range set
3. You can trim while the turing is running - it's much easier that way
