### ISSUE TITLE
Issue with sharf fin ramping on the output

### ISSUE THREAD

**Issue by ludotex** [TomWhitwell/TuringMachine#30]
My problem: 
It seems like the turing introduce some unwanted ramps of the main output at times. Sometimes it will even get stuck high, or low for a few seconds (see video)

Here is a video that shows the behavior. You can clearly see on the oscilloscope the ramps I am talking about. 

https://youtu.be/3ECbmk3Pn3U 

I have checked the resistances and ic positions and legs, and it looks good to me.
The only thing that I find weird is that when I measure the 470K Resistor (the one close to the diode) it reads 90K (maybe it's normal I dunno...).
I tried swapping the ICs that were the same but I still get the same problem.

Here is some pics of the build: 
![27950_20160529_183121_1](https://cloud.githubusercontent.com/assets/19728100/15775616/20ebdd72-2983-11e6-914d-ed50e4113542.jpg)
![27950_20160529_183142_1](https://cloud.githubusercontent.com/assets/19728100/15775621/2404d22a-2983-11e6-843b-91e3832af7ae.jpg)
![27950_20160529_183155_1](https://cloud.githubusercontent.com/assets/19728100/15775624/26a52f16-2983-11e6-8f04-fea796043792.jpg)
![27950_20160529_183210_1](https://cloud.githubusercontent.com/assets/19728100/15775625/2a11830c-2983-11e6-8c1c-87029cc68971.jpg)

Thanks for your help or advices on how to fix it.

**Comment by TomWhitwell** [comment]
I think the ramps are normal; if you think about how it works, it fixes a binary number and shifts it; so shifting from 
01000000
00100000
00010000
00001000
will cause an increase in output - a ramp. 
I can't quite tell from the video, but I'm not sure if loops are locking correctly. 
If you test it with 8 step sequences it's easier to tell what's going on. 
With shorter step sequences, there is a higher probability that the sequence will be 
111
or 
000
- i.e. locking high or low. 
With 8 steps, the probability of it becoming 
11111111
or
00000000
is lower - just in terms of coin tosses.

**Comment by ludotex** [comment]
Hello Tom,

Thank you for your quick reply. I will look at this in detail this weekend. 

Reading your explanation, it seems that it's working correctly after all then. I was expecting a more random signal without any ramps.

I think I can get a lock when the trimmer is almost fully counter clockwise.

**Comment by TomWhitwell** [comment]
If you want a different kind of CV output, the Volts expander is a configurable DAC - so the ramping effect doesn't happen - you can define how the binary is converted into CV

**Comment by ludotex** [comment]
Thanks. I will look into that sometimes.

Looking forward to do some music with the turing machine :)

Really enjoying your modules btw, have a radio music as well. I like the
different directions you take in your module concepts.


2016-06-03 14:30 GMT+02:00 Tom Whitwell <notifications@github.com>:
