### ISSUE TITLE
Trimming the Lock Question

### ISSUE THREAD

**Issue by soapdistant** [TomWhitwell/TuringMachine#33]
Hi! 

Not so much an issue, as i'm fairly sure my TM mkII is working, it lights up and makes all the right moves when i feed a clock into it.

My issue is, when i attempt to [trim the lock](https://vimeo.com/163160088), i've gone through the steps in the video but using a VCO from my Korg MS-20 Mini into the clock input, but the TM doesn't respond to the input. I get no indicator led on the clock in, the top led's remain constantly on, and I hear no output from the TM's out. 

Is this an indication that i may have messed up the build, or could it be that shouldn't be using an MS20-mini to generate the square wave? If so, is there another method i could use to trim the lock as i currently do not have a Eurorack VCO?

It's a great kit, was immense fun to build and i can't wait to start using it, 

Many thanks,

Soap

**Comment by Thonk-Steve** [comment]
Hey Soap,

It may be that the MS20-mini audio output is just far too quiet and outputting at the level of regular gear rather than modular levels. 

Steve

**Comment by soapdistant** [comment]
Hi Steve, thanks for the quick response! 

That's relieving to know i haven't messed up the build, presumably then i'll just need to amplify the output a bit? Would i be able to boost the signal enough using a Mackie Onyx 1220i Desk? Or would i need a specific line level to modular boosting option?

Many thanks again,

Soap

**Comment by Thonk-Steve** [comment]
Yeah that may well work, there's normally enough headroom on Mackie mixers, if you slowly increase the gain you may see it start to work... if the signal gets distorted too much it could cause some weirdness also though.

**Comment by soapdistant** [comment]
Thanks Steve, will give it a try!
