### ISSUE TITLE
diy osmosis

### ISSUE THREAD

**Issue by zaejin** [TomWhitwell/TuringMachine#39]
Hi, great fun building the kit but it seems there's a problem.
When it's attached to the power, it makes every socket in my modular output a clicky slow square tone.
Even on different modules. The other bits work okay when the turing isn't plugged in the power.

I'm using a synthrotek psu.
Cheers,
Victor.

**Comment by Thonk-Steve** [comment]
I would start by using a multimeter to check if you have continuity on the
Turing power connector between -12v and Gnd, +12v and Gnd or +12v and -12v.

Sounds like you have a short circuit in the Turing build somewhere to me.

**Comment by zaejin** [comment]
Hi thanks for your time.
There doesn't seem to be a short between those pins which I guess is where the whole of the circuit converges,
(i am a noob at this so I don't know where to look for shorts, those traces look awfully close).
I've had a look at all the solder joins and they seem ok.

**Comment by Thonk-Steve** [comment]
Hi, do you mean you tested with a meter or visually? The short will present
itself at the header to the meter but physically could be anywhere on
either board. You can't do this test visually.

**Comment by zaejin** [comment]
tested with a meter, yes. but I'm at passive mult level of skill here.

**Comment by TomWhitwell** [comment]
I'd double check that all the chips are the right way round and in the right places

**Comment by zaejin** [comment]
yeah they're checked to the build docs. all okay.

**Comment by Thonk-Steve** [comment]
Ok I think best thing to do is take photos of both sides of both PCBs and
we can take it from there

**Comment by zaejin** [comment]
Okay, taken some pictures as best I can without a tripod.
Many thanks for the effort.
![dscf1116](https://cloud.githubusercontent.com/assets/20258278/16566699/d5e20960-420e-11e6-9be9-14ada65f08ef.JPG)
![dscf1118](https://cloud.githubusercontent.com/assets/20258278/16566698/d5e02cb2-420e-11e6-9bb0-5d587bc1dc36.JPG)
![dscf1120](https://cloud.githubusercontent.com/assets/20258278/16566700/d5e46778-420e-11e6-8432-b3fa7633392b.JPG)
![dscf1122](https://cloud.githubusercontent.com/assets/20258278/16566701/d5e8d768-420e-11e6-82e1-0d07909ccf69.JPG)

**Comment by swahananda** [comment]
It looks like your 1n4001 on the back board are both oriented in the same direction. This is no bueno as diodes only allow power to flow through one direction and your -12 rail is currently aiming back into your system. The one on the bottom left of your image needs to be reversed.

**Comment by zaejin** [comment]
it works you f***ing wizard!! bit tricky resoldering the component but I managed it.
Thanks thanks thanks you efforts are appreciated thonk and friends.

**Comment by Thonk-Steve** [comment]
Ah it was nice to come check up and find this :)

**Comment by swahananda** [comment]
Oh heck yeah! Glad to be of some service! Now if only I can get my own Turings sorted, life will be even sweeter.
