### ISSUE TITLE
No sign of life. 

### ISSUE THREAD

**Issue by jestern77** [TomWhitwell/TuringMachine#43]
Assembled the complete kit as suggested in the docs. Seemed pretty easy. I plugged the TM (power + clock) nothing worked. Realized I forgot one 100nF cap on the ic (back) board. Soldered. Plugged in, no life. Checked all transformers to be correct and IC to be the right ones. Redid all solder points, still nothing. Sometimes when I unplug the power the two leds (clock and first bit) light up. Changed the TL074 (just in case) no sign of life.

Attached some pictures. Any clue? Maybe the lacking 100nF could have screwed up some IC? strange though...

![20160905_123119](https://cloud.githubusercontent.com/assets/6736085/18247024/12b8a64a-7370-11e6-92b1-a1bf8eba1d09.jpg)
![20160905_123137](https://cloud.githubusercontent.com/assets/6736085/18247025/12e75832-7370-11e6-849a-20236d211054.jpg)
![20160905_123150](https://cloud.githubusercontent.com/assets/6736085/18247026/12ea17c0-7370-11e6-8c1c-4e10b95b5f66.jpg)
![20160905_123202](https://cloud.githubusercontent.com/assets/6736085/18247027/12f0806a-7370-11e6-9669-cdb9c4741f02.jpg)

**Comment by TomWhitwell** [comment]
Can't see anything unusual in the pictures - have you made any progress? Does the clock LED flash when you connect it to a clock?

**Comment by jestern77** [comment]
HI Tom, no unfortunately doesn't work. The led doesn't lit up but the noise output does output noise. So the power goes there. Maybe some burned IC?

**Comment by TomWhitwell** [comment]
The clock input is the same chip as the noise generator, so it's hard to see how that could be. The 100nf would definitely not be a problem. 
It's a mystery - are you able to try it in another case? Do you have a friend with a working Turing you could compare it with? 
You could certainly try replacing the ICs, but it's an unusual case.

**Comment by jestern77** [comment]
hmm I refilled some of the holes, still no sign of life. Checked the LED orientation. I can send it to repair to a friend and see what went wrong...
