### ISSUE TITLE
Pulse outputs Failing

### ISSUE THREAD

**Issue by 123gravy** [TomWhitwell/TuringMachine#47]
Hey, 

 I have just put together the Turing machine plus volts and pulses expanders.  All working fine apart from the pulse output on the Turing machine itself and two outputs on the pulses expander (the '1+2' and '1+2+4+7'). There is no output from these at all. Has anyone experienced something like this? Or is there something I should try? Solder joints look ok

Thanks

**Comment by TomWhitwell** [comment]
Check orientation of all the chips on the back PCB of the main Turing module. Try swapping the AND chips to see if that makes a difference

**Comment by 123gravy** [comment]
Hi Tom,

 Thanks for the reply.  Orientation of the chips are all good.  Which chips
are the AND chips?

Isn't it strange that both the 1 output and the 2 output are all good but
not the 1+2 output on the Pulses?

Cheers

On 30 December 2016 at 22:31, Tom Whitwell <notifications@github.com> wrote:

Check orientation of all the chips on the back PCB of the main Turing
module. Try swapping the AND chips to see if that makes a difference




—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/TomWhitwell/TuringMachine/issues/47#issuecomment-269761552>,
or mute the thread

**Comment by Thonk-Steve** [comment]
Photos of the build would help, did you also double check the soldering of the expansion header on the main module? Do you have any other expander modules like Volts, Voltages etc?

**Comment by TomWhitwell** [comment]
You can also try connecting pulses to the gates header. That will tell you if the problem  is in the main module, or the pulses module.

**Comment by 123gravy** [comment]
Hi,

 Thanks for the replies.  Please excuse my slow reply, I was away from my rig for a few days.

I do have another expander, Volts.  Seems to be working ok.  

The solder joints of the expansion headers look ok to me but I'll attach a few photos. 

I attached the Pulses module to the Gates header on the Turing Machine and the Pulse output on the Turing Machine then works, but still not the two (the '1+2' and '1+2+4+7') outputs on the Pulses module.  What does that suggest there must be an issue with both the TM and the Pulses builds?  Sorry to be a pain


![img_2008](https://cloud.githubusercontent.com/assets/24840228/21636034/13367af8-d2b5-11e6-9217-9b1eae5f6b27.JPG)
![img_2015](https://cloud.githubusercontent.com/assets/24840228/21636036/13825806-d2b5-11e6-9ecd-c2a98ddca6d1.JPG)
![img_2016](https://cloud.githubusercontent.com/assets/24840228/21636039/138afd58-d2b5-11e6-8525-bb06d897f3c6.JPG)
![img_2019](https://cloud.githubusercontent.com/assets/24840228/21636037/1385458e-d2b5-11e6-82d6-7fc565f18092.JPG)
![img_2030](https://cloud.githubusercontent.com/assets/24840228/21636038/13880b7a-d2b5-11e6-8d5e-ed672b9626e3.JPG)
![img_2004](https://cloud.githubusercontent.com/assets/24840228/21636040/138ebf60-d2b5-11e6-8774-742ec3b643b6.JPG)
![img_2123](https://cloud.githubusercontent.com/assets/24840228/21636035/1363145a-d2b5-11e6-81b5-917f27b33f3e.JPG)
![img_2032](https://cloud.githubusercontent.com/assets/24840228/21636041/139109c8-d2b5-11e6-94e5-bfef103b40b9.JPG)

**Comment by 123gravy** [comment]
I double checked all of the expander headers and re-soldered a couple of pins that looked as though the solder hadn't gone through to the other side quite as well when you pry up the black pin support on the header.  Still all the same

**Comment by 123gravy** [comment]
I've checked all of the jacks on the Pulses with a beep test.  All fine.  Re-soldered the IC as it was a bit rough.  Still the same.  I'm convinced that it is just the Pulses module.  I just can't suss out which component...
![img_2133](https://cloud.githubusercontent.com/assets/24840228/21639836/61fe69d2-d2c6-11e6-9a0a-9ed9054b5b3e.JPG)
![img_2129](https://cloud.githubusercontent.com/assets/24840228/21639837/6258989e-d2c6-11e6-8dd5-0933074c9b1d.JPG)
![img_2132](https://cloud.githubusercontent.com/assets/24840228/21639838/625fde24-d2c6-11e6-8c71-b58cad1dbb76.JPG)
![img_2130](https://cloud.githubusercontent.com/assets/24840228/21639839/62613008-d2c6-11e6-909c-4745198af1aa.JPG)
![img_2131](https://cloud.githubusercontent.com/assets/24840228/21639840/62638c2c-d2c6-11e6-8eaa-eda549c91d2e.JPG)

**Comment by 123gravy** [comment]
The Pulse output on the Turing Machine also works fine without any expanders attached

**Comment by 123gravy** [comment]
I should also mention that the outputs of the Pulses do not carry pitch but they do give a signal.  I've been using them to trigger drums which works fine.  However when I send the signal to an oscillator they each trigger in only one pitch.  Every output has the same pitch except for output 1 which has a higher repeated pitch, no variation following the turing machine...

**Comment by TomWhitwell** [comment]
Pulses outputs are triggers - normally low (below 1v) becoming high (roughly 8v) when they are active. They're not expected to have any pitch content.

**Comment by 123gravy** [comment]
Ah ok. I only got that impression from this video https://youtu.be/Le26BIqB8Y8 about 14 mins in. I can't see the full patch though.  So that's that query sorted. Thanks. Can you make any sense of the rest. (The 2 outputs not working on the pulses and the pulse output not working on the Turing machine only when the pulses is plugged in)?

**Comment by TomWhitwell** [comment]
Sounds like a soldering problem around the chip on the expander

**Comment by 123gravy** [comment]
Ok cheers. I did touch up some soldering around the chip and nothing changed. It still could be better though so I'll try removing it altogether and starting fresh. Thanks

**Comment by 123gravy** [comment]
![img_2248](https://cloud.githubusercontent.com/assets/24840228/21802229/eefd9ee6-d778-11e6-89a7-35d4246cb434.JPG)
Hello again Tom.  OK so i re-soldered it again and this time also lost outputs 4, 2+4, and 4+7.  I touched it up again and managed to get it back to just missing the original 1+2 and 1+2+4+7.  As you can see from this photo I've made a dogs dinner of the PCB.  You can see some copper next to the IC.
 I'm wondering maybe if I've knackered the IC? Or now possibly the PCB?  Or both.  Would it be worth getting a new IC do you think?  Or have I killed this one?  Sorry to be a pain in the arse

**Comment by TomWhitwell** [comment]
Hi, - that doesn't look great - I can't really tell from the pictures, but it looks like there could be any number of shorts between the IC pins. If you have access to a hot air soldering gun, lots of flux and soldering braid, it might be possible to clean it up, but tricky...

**Comment by 123gravy** [comment]
I do have a bit of flux and braid.  Yeah to be honest I haven't really been using the flux.  I'll give it a proper go again using those.  So you wouldn't be too worried about the exposed copper on the PCB?

**Comment by TomWhitwell** [comment]
If it's just exposed, that's probably OK so long as nothing is shorting onto it.

**Comment by 123gravy** [comment]
Ok, thanks

**Comment by 123gravy** [comment]
Hey Tom,

 Cleaned up the IC.  Re-soldered like a machine! Same drama.  Re-soldered all resistors.  All working like a dream, Turing machine, volts and pulses.  Must have been a bad contact thing with the resistors on the Pulses.  Awesome kits! How annoying is ametures must be.  Cheers
