### ISSUE TITLE
No output from main module's pulse out, no LEDs for pulse or clock

### ISSUE THREAD

**Issue by jrennis** [TomWhitwell/TuringMachine#54]
Just finished my Turing Machine mkii. Everything seems to work except for the LEDs above the clock and pulse out. Clock seems to work, but I don't think pulse out is doing anything. I'm not sure because I cannot seem to find any indication online about quite what it does but I can guess.

Any ideas on where I should start looking for bad soldering? Very much appreciated.

**Comment by TomWhitwell** [comment]
Hi, did you make any progress on this? I'd check for orientation of those LEDs. Pulse out is a single clock pulse every time stage 1 is lit.
