### ISSUE TITLE
No Clock LED, No Output, build not working

### ISSUE THREAD

**Issue by bertog** [TomWhitwell/TuringMachine#60]
Hi,

I've just finished my second TM build and this time I've some issue. The module power up but when I plug the square signal in the clock input there's no LED activity or audio output (seems something but very very very low). The DAC0800 become also immediately very hot. Some advice to begin some trouble shooting?

Some picture of my build:

![image](https://cloud.githubusercontent.com/assets/7644360/26651724/f27ad004-464d-11e7-8ce9-d480562bcc9d.png)
![image](https://cloud.githubusercontent.com/assets/7644360/26651739/0132cfca-464e-11e7-99e0-7b94fa4a862d.png)
![image](https://cloud.githubusercontent.com/assets/7644360/26651778/1898b9b8-464e-11e7-9360-687c24756c17.png)
![image](https://cloud.githubusercontent.com/assets/7644360/26651793/23035ec6-464e-11e7-94e6-aaa28ad92615.png)

Thank you very much. Guido Bertolino

**Comment by Thonk-Steve** [comment]
Do you still have your successful build?
Have you checked with a multimeter for a short between +12v and gnd, or -12v and gnd?

**Comment by bertog** [comment]
Hi Steve,

Yes I've access to the other build. 

I've checked now and I've no short.

G.

**Comment by Thonk-Steve** [comment]
I would suggest trying a combination of front and rear PCBs with the working build, then at least you can find out which board is faulty? You tested for shorts with the defective PCBs mated together?

**Comment by bertog** [comment]
Thanks for the help.

I've matched the rear PCB of successful build with the jack pcb of the faulty and everything is working. I've successfully calibrated the module. 

So the problem is on the rear PCB. 

I've check for short with the mated PCBs and now only on the rear, but seems there's no shorts

G.

**Comment by bertog** [comment]
Ok Steve,

I've founded the problem ... there was a small piece of lead touch one of the IC solder joint ... 

I've removed it and now is working ... 

Sorry and thank you very much for the help ... I'm newbie so I fall in panic very early, but tonight I've learned some troubleshooting ... Thanks again :) Guido

**Comment by Thonk-Steve** [comment]
great, just talking about and trying new angles often shakes these things out :)
