### ISSUE TITLE
New build not working (no bits being generated?)

### ISSUE THREAD

**Issue by digable-me** [TomWhitwell/TuringMachine#63]
Hi,

This Turing Machine MkII is my first build (after some practice bits and pieces) so I'm sure these issues are down to my amateur-ness.

So, this is the issue:

- When powered on with nothing plugged in the whole top row of LEDs lights up except the left most one.

- Clock input, pulse output, noise output, all seem to work fine.

- When I supply a clock input the top LEDs turn off in sequence but no new bits are being generated and the LEDs remain off until I push up on the WRITE switch. Then bits are generated on the LEDs and on the output, but no bits are subsequently spontaneously generated.

- With an audio rate CV input, listening to the main OUT, pushing the WRITE switch upwards creates a brief tone at the output followed immediately by a static voltage offset. The offset falls to zero once the WRITE switch is released. The LEDs remain lit for as long as the WRITE switch is held up, but the tone on the OUT is brief. Tweaking the trimmer does not seem to have any effect.

Here are some pics of my build:

![fullsizerender-1](https://user-images.githubusercontent.com/29688858/27516220-98d3123c-59ad-11e7-99fe-4fffa87ac1b7.jpg)
![fullsizerender-2](https://user-images.githubusercontent.com/29688858/27516223-98da4fa2-59ad-11e7-82d9-9de599eced65.jpg)
![fullsizerender](https://user-images.githubusercontent.com/29688858/27516222-98d984be-59ad-11e7-8640-10c8bdc9b5d6.jpg)
![img_1406](https://user-images.githubusercontent.com/29688858/27516221-98d57fc2-59ad-11e7-99f2-4ea639c1931f.JPG)

Many thanks for any help. Really excited about this module and truly hope I can get it working asap.

**Comment by TomWhitwell** [comment]
It looks like you've used a 40106 instead of a 4016 

The 40106 is a [super useful chip](http://milkcrate.com.au/_other/sea-moss/), but not in this module. 

![image](https://user-images.githubusercontent.com/1890544/27516776-63ed534c-59b8-11e7-9ad3-dae76e6c03a5.png)

**Comment by digable-me** [comment]
Hi. That's all the module came with. I bought a full kit from Thonk.

**Comment by TomWhitwell** [comment]
Oh, OK, sorry to hear that, I'm sure Thonk can get you a replacement - I'll also CC this thread to them. Good news is that I don't think the chip will damage the rest of the circuit, so you should just be able to swap in the right one.

**Comment by digable-me** [comment]
Ok thanks. I'll send them an email now.

**Comment by digable-me** [comment]
And many thanks for the super quick response.

**Comment by Thonk-Steve** [comment]
Hi digable-me, I thought i'd tracked all these down so sorry about this. drop us a mail on support@thonk.co.uk

The good news is the chip won't have damaged your module.

**Comment by digable-me** [comment]
Thanks. Email sent.
