### ISSUE TITLE
Clock LED doesn't trigger and all lights come on at the top, don't change.

### ISSUE THREAD

**Issue by calmoo** [TomWhitwell/TuringMachine#64]
So i finished the build today. I've double checked all components and solder joints.

When I turn it on, all the lights at the top of the Turing Machine come on. The clock LED doesn't respond to a clock source at all. Sometimes when I turn it on, the top left LED stays off while the others stay on. The knobs don't change anything. The noise output works.

Not sure what I'm missing?

**Comment by TomWhitwell** [comment]
Check around the TL074 on the front board - that's the clock circuit - it's possibly a missed solder point there or on the clock input. If noise is working, then that TL074 is working - receiving power etc, so it's likely to be a missing solder joint or component. 
![image](https://user-images.githubusercontent.com/1890544/27612059-a8d23592-5b8c-11e7-92e0-2cdb98c5ed16.png)

**Comment by calmoo** [comment]
Figured out that the clock source I was feeding from my phones LFO
generator volume  was too low. Daisy chained it from a doepfer envelope
generator and it worked a charm. Thanks Tom!
