### ISSUE TITLE
Only 12 100n capacitors not 13 in the pack...

### ISSUE THREAD

**Issue by Latzenpratz** [TomWhitwell/TuringMachine#66]
Hi! The building manual and the BOM states there are 13 100n caps.
My package only has 12 100n caps, the bag with the caps also states 12 100n caps...
Is this a newer version? Which cap is different and what value?

**Comment by Thonk-Steve** [comment]
Ah it is only 12 you need, it's an old mistake carried forward. You'll see that on the BOM and the bag there are only 12 designators.

**Comment by Latzenpratz** [comment]
Thanks for the quick answer!!
