### ISSUE TITLE
can't calibrate, get a kind of sinus sound...

### ISSUE THREAD

**Issue by Latzenpratz** [TomWhitwell/TuringMachine#67]
Hi!

just finished my build. I'm trying to calibrate, but the main pot and the calibration pot don't do anything. Length, write and scale seem to work. I here something like a sine wave played with  the set length, but no randomness.

**Comment by Thonk-Steve** [comment]
Would it be possible to upload a video demonstrating your problem?

**Comment by Latzenpratz** [comment]
Thanks for the quick response!
I'll try to make a video next weekend...

**Comment by Latzenpratz** [comment]
Hi! 
I noticed that the Turing triggers my maths without connecting it (i can hear the turing output from the maths output). The only connection between them is the power board...
So i'm to scared for now to reinstall the turing and make a video.
Maybe you can see an error on the pics:
![20170705_215141](https://user-images.githubusercontent.com/29898377/28173436-be2a8e80-67ee-11e7-8bf1-5efc873cca0e.jpg)
![20170705_215155](https://user-images.githubusercontent.com/29898377/28173435-be27cf7e-67ee-11e7-88d7-7e990af11a30.jpg)
![20170705_215213](https://user-images.githubusercontent.com/29898377/28173433-be250fd2-67ee-11e7-8d0c-6a4147f4c3e2.jpg)
![20170705_215222](https://user-images.githubusercontent.com/29898377/28173434-be253412-67ee-11e7-823f-b15c13252603.jpg)

**Comment by Latzenpratz** [comment]
On my MDLR busboard the -12v LED doesn't light up if i install the turingmachine, so it seems there is a short-circuit or something... help...

**Comment by Thonk-Steve** [comment]
Use a multimeter continuity tester to see if you have continuity between:

+12v and gnd
+12v and -12v
-12v and gnd

**Comment by Latzenpratz** [comment]
yes, continuity between -12v and gnd

**Comment by Thonk-Steve** [comment]
yeah I would start looking along the -12v lines and see if you have any
shorts

**Comment by Latzenpratz** [comment]
yes the short must be on the board with the music thing print. i'll do my very best ;-) THANKS!

**Comment by Thonk-Steve** [comment]
yeah it is worth taking the PCBs apart just to double check which board
it's on.

**Comment by Latzenpratz** [comment]
I can't see any visible short, where are good points to break the circuit to narrow down the place of the short?

**Comment by Latzenpratz** [comment]
Found it!  :yay: 
One diode was faulty, after removing it the turing machine works!
