### ISSUE TITLE
TuringMachine not working at all

### ISSUE THREAD

**Issue by dorkajef** [TomWhitwell/TuringMachine#71]
Hello,
Finished My DIY for the Turing machine yesterday. But it did not show any traces of life -> no noise, it did not blink lights, did not effect the OSC when patching, did not react to clock signal.
I did check My solders couple of times, double checked also the parts -> everything should be ok (but after one check the upper light when on ((but no reaction to clock, etc...) -> and when I unplug the device and put all the nuts on -> again no lights.
I know that My solder is not the best A+, but all My DIY units have worked until now.
Would you have an idea what´s wrong?

Best Regards
Thomas
![20614134_10156077318919749_666845405_n](https://user-images.githubusercontent.com/30659465/28913062-5c7dbc1e-783f-11e7-9bd0-385c3106f5c7.jpg)
![20614370_10156077320994749_1719231109_n](https://user-images.githubusercontent.com/30659465/28913058-5c468aaa-783f-11e7-8a7b-45c77c311c77.jpg)
![20623868_10156077321344749_241385133_n](https://user-images.githubusercontent.com/30659465/28913060-5c49a618-783f-11e7-9ce7-7b8eff0f5a5d.jpg)
![20631801_10156077319374749_1294574532_n](https://user-images.githubusercontent.com/30659465/28913061-5c4d2a0e-783f-11e7-94b2-4eebb5ff8024.jpg)

**Comment by TomWhitwell** [comment]
Hi, sorry to hear that. When I have problems like that, it's often because I've done something extra stupid - like not turning on the power, not connecting the other end of the power cable etc. 
One thing you could try is - if you have  multimeter - checking that you're getting the appropriate power to the chips - i.e. separate the boards, plug the back board into power, and check there is (roughly) 24v difference between pin4 (black probe) and pin8 (red probe) on the little TL072. That will tell you if there's a basic problem with power. If the back board is OK, carefully check the soldering on the connector pins between the back and front boards - if the front board isn't getting any power, you'd get the symptoms you describe.

**Comment by dorkajef** [comment]
Thanks Tom for the Quick answer. 
Gonna try that tonight after I come home. 
Best
Thomas

**Comment by dorkajef** [comment]
Hello,
I think I may found the problem. There is a shortcut in the six pin header (the middle one on the back board). Could this mistake have fried my parts?
Thanks!
-Thomas

**Comment by TomWhitwell** [comment]
Possibly not - that connects +12 to -12v, which I'd imagine would cause your case power supply to shut down quite fast - fix it, check there's no more connectivity, and test to see

**Comment by dorkajef** [comment]
Hi,
Just to make sure that we are speaking from the same part... 
I removed the connection part, and try to clean the area, but if I assume right the PCB has jumpers between pins 1&4, 3&6, and on the other side 2&5 (but I quite n00b with these things;).
I´m just wondering because my meter is beeping with these connections (also with the upper PCB).
Best Regards
Thomas
![20624072_10156078700619749_1039947523_n](https://user-images.githubusercontent.com/30659465/28930668-5854011a-787c-11e7-9b33-d15419270cd8.jpg)
![20624584_10156078699979749_951238418_n](https://user-images.githubusercontent.com/30659465/28930669-587d0e34-787c-11e7-87b2-cb8a73dda71b.jpg)

**Comment by TomWhitwell** [comment]
This is how they're connected: 
![image](https://user-images.githubusercontent.com/1890544/28931245-58388818-786d-11e7-9ea3-b98115412b17.png)

**Comment by dorkajef** [comment]
Sorry my bad, I did mistakenly assume who those are counted -> so no shortcut there, they where as they should be. 
I did also measure the power as You instructed -> and I got a reading of about 25 Vdc and 52 Vac.
Did also solder all the connector pins newly (at that moment I mistakenly noticed that so called shortcut). So any ideas?
Best Regards
-Thomas

**Comment by dorkajef** [comment]
Hi,
I did also test the connection pins while the boards are connected, the connections works - but I also noticed that on the upper board has also an connection beteeen +12 & GND somewhere (this is normal, I suppose).

-Thomas

**Comment by TomWhitwell** [comment]
No, there shouldn't be a connection between +12 and GND - that would also the problem.

**Comment by dorkajef** [comment]
Ok, I´m on the trace. 
I did try to find out where the GND goes (but can´t see it from the PCB), and I´m not enough seasoned to read it from the schematics. So if you can advice Me (then I maybe could find the shortcut).
Thanks
-Thomas

**Comment by TomWhitwell** [comment]
GND lives on the ground plane - it's all the copper on the bottom that isn't part of another trace: 
![image](https://user-images.githubusercontent.com/1890544/28958798-a4c1f91c-78ef-11e7-913e-fd388bff152e.png)

**Comment by dorkajef** [comment]
Ok, thanks.
So non of the GND points should make a connection with +12?
-Thomas

**Comment by TomWhitwell** [comment]
Definitely not

**Comment by dorkajef** [comment]
Hi,
Have been looking for any solder shortcuts (could not find any). I even removed some parts (all capacitors but not: c17, c14 & c9).  The IC´s I removed in the beginnin of this operation. 
Still a shortcut when measuring Link2 pins 6&4 (+12 & GND).
Any idea where / what path I could try to find next?
Thanks for the help.
-Thomas

**Comment by TomWhitwell** [comment]
Do you think the back board (with the power connector) is OK? Is that's where you tested the PCB voltages on the TL072?

Separate the boards, remove the two ICs from the front board, and see if there is still a short between +12v and GND

**Comment by dorkajef** [comment]
Yes that is what I did. I assume that the back board was ok (measured the voltages as described -> ok), the pins had no short between the pins (when measured the back board separate)- > So I´m quite sure the problem is on the front panel.
