### ISSUE TITLE
CALIBRATION problem

### ISSUE THREAD

**Issue by BORSCH2503** [TomWhitwell/TuringMachine#79]
Hi!
Just finishing my module! Everything works fine. Pulse out works.I hear a noise from the noise output between pulses.Is it ok?
But i have some problems with the calibration.
When i try to calibrate square tone became stable only when trimmer pot is completely CCW.
And something wrong with lock function-it locks on 12 o clock and make random on CW position.

**Comment by TomWhitwell** [comment]
"And something wrong with lock function-it locks on 12 o clock and make random on CW position"
This sounds like some kind of construction error - a missed solder point, or a short circuit somewhere.

**Comment by BORSCH2503** [comment]
When i listen to noise output and rotate the trimmer noise volume don't decrease as i think it should!
Its go to silent only at full CCW position and full volume at any other?
Works like a on/off!
Any thoughts?

**Comment by TomWhitwell** [comment]
Again, check the soldering - look for any short circuits or chips the wrong way around.

**Comment by adiogo08** [comment]
@TomWhitwell hi Tom.  Just finished my build as well.  I can't seem to get it to calibrate with out being all the was counter clock wise.  Could this be to not using a proper VCO square wave.   I have a erica synths wavetable and a make noise sto.

**Comment by TomWhitwell** [comment]
@adiogo08 See if the module works properly as a sequencer at normal LFO rates (rather than audio rates for calibration) - it should clock OK to the STO or Erica Wavetable.
