### ISSUE TITLE
TURING MACHINE GENESIS

### ISSUE THREAD

**Issue by BertrandLenclos** [TomWhitwell/TuringMachine#81]
Hi Tom,
I'm Bertrand from France.
Very happy with the Music Thing modules I've bought. Turing machine MK2 makes a great job in all my patches.
I'm working now on a theater show project called TURING TEST. This is about A.I. and it's a mix of performance with robots, animated movies made live on stage and electronic music. I'm in a writing phase and I'm curious about the links between your module and the original Alan Turing's mathematical model describe in 1936. The infinite linear tape delivering various states ? How this thought exercise has inspired you ? I will be very happy if you can tell me in few words what was in your mind when you created this and what part of the original concept remains in the final module.
Thank you for that. Best regards

**Comment by TomWhitwell** [comment]
The module have a sense of a repeating loop with a 'record/play head' that can make changes to the contents of the loop.
Obviously it is NOT a Turing machine, but the module name was inspired by that connection - and as a tribute to a great British hero...
