### ISSUE TITLE
first power on; leds turn on then slowly turn off, Little fuse HOT

### ISSUE THREAD

**Issue by omidderham** [TomWhitwell/TuringMachine#88]
Hi,

When i turn on my turing machine for the first time, the leds power on and immedeately start going dim. I can feel the little fuse is getting hot. What can this be ?

Best regards,
Olivier.

**Comment by Thonk-Steve** [comment]
you have a short circuit somewhere or are maybe plugging power in backwards
or with power cable offset to pins?

**Comment by omidderham** [comment]
Thanks,
reinserting all the IC's did the trick. Onwards to trimming !
Thanks,
Regards Olivier.
